import telnetlib,time
print('--------------telnet登录华为防火墙-----------------')
USG = {'hostname':'10.1.1.21','username':'admin','password':'Huawei@123'}
Huawei_tn = telnetlib.Telnet(USG['hostname'])
Huawei_tn.read_until(b'Username:')
Huawei_tn.write(USG['username'].encode('ascii') + b'\n')
Huawei_tn.read_until(b'Password:')
Huawei_tn.write(USG['password'].encode('ascii') + b'\n')
Huawei_tn.write(b'sys\n')
Huawei_tn.write(b'int G1/0/0\n')
Huawei_tn.write(b'ip add 10.1.5.21 24\n')
Huawei_tn.write(b'fire zon dmz\n')
Huawei_tn.write(b'add int G1/0/0\n')
Huawei_tn.write(b'return\n')
Huawei_tn.write(b'sa\n')
Huawei_tn.write(b'y\n')
time.sleep(3)
Huawei_tn.write(b'quit\n')            #Python3的telnetlib中quit为断开telnet连接，此时就不能使用read_all()
output = Huawei_tn.read_very_eager().decode('ascii')
print (output)
Huawei_tn.close()
print('--------------telnet登录思科路由器-----------------')
Cisco = {'hostname':'10.1.1.22','username':'python','password':'Huawei@123','secret':'Huawei@123'}
Cisco_tn = telnetlib.Telnet(Cisco['hostname'])
Cisco_tn.read_until(b'Username:')
Cisco_tn.write(Cisco['username'].encode('ascii') + b'\n')
Cisco_tn.read_until(b'Password:')
Cisco_tn.write(Cisco['password'].encode('ascii') + b'\n')
Cisco_tn.read_until(b'>')
Cisco_tn.write(b'enab' + b'\n')
Cisco_tn.write(Cisco['secret'].encode('ascii') + b'\n')
Cisco_tn.write(b'conf t\n')
Cisco_tn.write(b'int Gi0/1\n')
Cisco_tn.write(b'no shu\n')
Cisco_tn.write(b'ip add 172.16.1.22 255.255.255.0\n')
Cisco_tn.write(b'end\n')
Cisco_tn.write(b'wr\n')
Cisco_tn.write(b'exit\n')
print (Cisco_tn.read_all().decode('ascii'))

